Repository Digital-Thread/sup, pull requests merged in 2024-11, with the labels that each got.

#23 feat(project): impl project
  src/api/controllers/__init__.py
  src/api/controllers/project.py
  src/api/dtos/project_dtos.py
  src/apps/project/domain/__init__.py
  src/apps/project/domain/entity/__init__.py
  src/apps/project/domain/entity/project.py
  src/apps/project/domain/types_ids.py
  src/apps/project/dtos.py
  src/apps/project/exceptions.py
  src/apps/project/i_project_repository.py
  src/apps/project/mapper.py
  src/apps/project/use_cases/__init__.py
  src/apps/project/use_cases/create_project.py
  src/apps/project/use_cases/delete_project.py
  src/apps/project/use_cases/get_projects_by_workspace_id.py
  src/apps/project/use_cases/update_project.py
  src/data_access/converters/project_converter.py
  src/data_access/models/__init__.py
  src/data_access/models/project.py
  src/data_access/models/project_participants.py
  src/data_access/reposotiries/project_repository.py
  src/main.py
  src/providers/adapters.py
  src/providers/usecases.py
Labels: enhancement

#21 feat(comment): add endpoints
  src/api/controllers/comment.py
  src/api/exc_handlers.py
  src/apps/comment/__init__.py
  src/apps/comment/domain/protocols.py
  src/apps/comment/domain/value_objects.py
  src/apps/comment/dtos.py
  src/apps/comment/interactors/__init__.py
  src/apps/comment/interactors/add_comment.py
  src/apps/comment/interactors/delete_comment.py
  src/apps/comment/interactors/fetch_comment.py
  src/apps/comment/interactors/update_comment.py
  src/data_access/reposotiries/comment.py
  src/providers/adapters.py
  src/providers/usecases.py
Labels: enhancement

#27 bugfix(develop): models and provider
  src/api/controllers/__init__.py
  src/api/controllers/feature.py
  src/api/exc_handlers.py
  src/apps/feature/interactors/base_interactor.py
  src/apps/feature/interactors/get_features.py
  src/data_access/models/__init__.py
  src/data_access/models/feature.py
  src/data_access/models/project.py
  src/data_access/models/user.py
  src/data_access/models/workspace_models/category.py
  src/data_access/models/workspace_models/tag.py
  src/data_access/models/workspace_models/workspace.py
  src/data_access/repositories/__init__.py
  src/main.py
  src/providers/adapters.py
  src/providers/usecases.py
Labels: bug

#29 feat(user, workspace_invite): create workspace after registration
  src/api/controllers/user.py
  src/api/controllers/workspace_invite.py
  src/apps/workspace/repositories/i_workspace_invite_repository.py
  src/apps/workspace/use_cases/workspace_invite_use_cases/__init__.py
  src/apps/workspace/use_cases/workspace_invite_use_cases/get_workspace_invite.py
  src/apps/workspace/use_cases/workspace_invite_use_cases/update_workspace_invite.py
  src/apps/workspace/use_cases/workspace_use_cases/__init__.py
  src/apps/workspace/use_cases/workspace_use_cases/add_member_in_workspace.py
  src/data_access/models/__init__.py
  src/data_access/models/project_participants.py
  src/data_access/repositories/workspace_invite_repository.py
  src/providers/usecases.py
Labels: enhancement

#30 hotfix(ci): fixed pip version
  .github/workflows/lint.yml
Labels: bug

#28 bugfix(feature): api and linting issues
  src/api/controllers/feature.py
  src/api/dtos/feature.py
  src/apps/feature/exceptions.py
  src/apps/feature/interactors/base_interactor.py
  src/apps/feature/repositories/feature_repository.py
  src/data_access/repositories/feature/mapper.py
  src/data_access/repositories/feature/sql_alchemy_repository.py
Labels: bug

#31 feat(task): implement task feature
  src/api/controllers/__init__.py
  src/api/controllers/feature.py
  src/api/controllers/task.py
  src/api/dtos/task.py
  src/api/exc_handlers.py
  src/apps/feature/service.py
  src/apps/task/__init__.py
  src/apps/task/domain/__init__.py
  src/apps/task/domain/aliases.py
  src/apps/task/domain/entities/__init__.py
  src/apps/task/domain/entities/task.py
  src/apps/task/dtos.py
  src/apps/task/exceptions.py
  src/apps/task/interactors/__init__.py
  src/apps/task/interactors/base_interactor.py
  src/apps/task/interactors/create_task.py
  src/apps/task/interactors/delete_task.py
  src/apps/task/interactors/get_task_by_id.py
  src/apps/task/interactors/get_tasks.py
  src/apps/task/interactors/update_task.py
  src/apps/task/repositories/__init__.py
  src/apps/task/repositories/task_repository.py
  src/data_access/converters/feature_converter.py
  src/data_access/converters/task_converter.py
  src/data_access/models/__init__.py
  src/data_access/models/feature.py
  src/data_access/models/task.py
  src/data_access/models/user.py
  src/data_access/models/workspace_models/tag.py
  src/data_access/models/workspace_models/workspace.py
  src/data_access/repositories/__init__.py
  src/data_access/repositories/feature_repository.py
  src/data_access/repositories/task_repository.py
  src/main.py
  src/providers/adapters.py
  src/providers/usecases.py
Labels: enhancement

#25 [WIP] feat(docs): add initial docs
  DEVELOPMENT.md
  LICENSE
  README.md
  assets/logo.svg
Labels: documentation

#34 feat(user): added create workspace after create user by admin
  src/api/controllers/user.py
  src/apps/user/services/create_user_service.py
Labels: enhancement

#35 test(workspace): add unit test for workspace domain
  src/apps/workspace/domain/entities/category.py
  src/apps/workspace/domain/entities/role.py
  src/apps/workspace/domain/entities/tag.py
  src/apps/workspace/domain/entities/validator_mixins.py
  src/apps/workspace/domain/entities/workspace.py
  src/apps/workspace/domain/entities/workspace_invite.py
  tests/fixtures/__init__.py
  tests/fixtures/workspace_fixtures.py
  tests/workspace/__init__.py
  tests/workspace/unit/__init__.py
  tests/workspace/unit/test_category_domain.py
  tests/workspace/unit/test_role_domain.py
  tests/workspace/unit/test_tag_domain.py
  tests/workspace/unit/test_workspace_domain.py
  tests/workspace/unit/test_workspace_invite_domain.py
Labels: test

#38 feat(project): refactor and add use case for get project with workspace members
  src/api/controllers/project.py
  src/api/dtos/project.py
  src/apps/project/domain/entity/__init__.py
  src/apps/project/domain/project.py
  src/apps/project/dtos.py
  src/apps/project/interactors/__init__.py
  src/apps/project/interactors/create_project.py
  src/apps/project/interactors/delete_project.py
  src/apps/project/interactors/get_projects_by_workspace_id.py
  src/apps/project/interactors/update_project.py
  src/apps/project/mapper.py
  src/apps/project/project_repository.py
  src/apps/project/use_cases/__init__.py
  src/apps/project/use_cases/get_project_by_id.py
  src/data_access/mappers/project_mapper.py
  src/data_access/repositories/project_repository.py
  src/main.py
  src/providers/adapters.py
Labels: enhancement, refactoring

#39 feat(workspace): api for get entity(role, tag, category)
  src/api/controllers/category.py
  src/api/controllers/role.py
  src/api/controllers/tag.py
  src/api/dtos/category.py
  src/api/dtos/role.py
  src/api/dtos/tag.py
  src/apps/workspace/dtos/category_dtos.py
  src/apps/workspace/dtos/role_dtos.py
  src/apps/workspace/dtos/tag_dtos.py
  src/apps/workspace/interactors/category_interactors/get_category_by_id.py
  src/apps/workspace/interactors/category_interactors/get_category_by_workspace.py
  src/apps/workspace/interactors/role_interactors/get_role.py
  src/apps/workspace/interactors/tag_interactors/get_tag.py
  src/apps/workspace/interactors/tag_interactors/get_tag_by_workspace.py
  src/apps/workspace/mappers/category_mapper.py
  src/apps/workspace/mappers/tag_mapper.py
  src/providers/usecases.py
Labels: enhancement
