Repository Digital-Thread/sup, pull requests merged in 2025-02, with the labels that each got.

#55 refactor(project): get workspace context in controllers, move error handling, add pagination
  src/api/controllers/project.py
  src/api/dtos/project.py
  src/api/exc_handlers.py
  src/apps/project/dtos.py
  src/apps/project/interactors/create_project.py
  src/apps/project/interactors/delete_project.py
  src/apps/project/interactors/get_projects_by_workspace_id.py
  src/apps/project/interactors/update_participants.py
  src/apps/project/interactors/update_project.py
  src/apps/project/mapper.py
  src/apps/project/project_repository.py
  src/apps/project/use_cases/get_project_by_id.py
  src/data_access/mappers/project_mapper.py
  src/data_access/migrations/versions/2025_01_14_1109-8cecbc6af290_.py
  src/data_access/repositories/project_repository.py
Labels: refactoring

#56 refactor(project): get workspace context in controllers, move error handling, change responses
  src/api/controllers/project.py
  src/api/dtos/project.py
  src/api/exc_handlers.py
  src/apps/project/dtos.py
  src/apps/project/interactors/create_project.py
  src/apps/project/interactors/delete_project.py
  src/apps/project/interactors/get_projects_by_workspace_id.py
  src/apps/project/interactors/update_participants.py
  src/apps/project/interactors/update_project.py
  src/apps/project/mapper.py
  src/apps/project/project_repository.py
  src/apps/project/use_cases/get_project_by_id.py
  src/data_access/mappers/project_mapper.py
  src/data_access/migrations/versions/2025_01_14_1109-8cecbc6af290_.py
  src/data_access/repositories/project_repository.py
Labels: enhancement, refactoring

#58 Refactoring the comment context
  src/api/controllers/comment.py
  src/api/dtos/comment.py
  src/api/exc_handlers.py
  src/apps/comment/__init__.py
  src/apps/comment/converters.py
  src/apps/comment/domain/__init__.py
  src/apps/comment/domain/comment.py
  src/apps/comment/domain/entity.py
  src/apps/comment/domain/event.py
  src/apps/comment/domain/protocols.py
  src/apps/comment/domain/types_ids.py
  src/apps/comment/domain/value_objects.py
  src/apps/comment/dtos.py
  src/apps/comment/exceptions.py
  src/apps/comment/interactors/__init__.py
  src/apps/comment/interactors/add_comment.py
  src/apps/comment/interactors/base_interactor.py
  src/apps/comment/interactors/create_comment.py
  src/apps/comment/interactors/delete_comment.py
  src/apps/comment/interactors/fetch_comment.py
  src/apps/comment/interactors/get_by_feature_id.py
  src/apps/comment/interactors/get_by_task_id.py
  src/apps/comment/interactors/update_comment.py
  src/apps/comment/mapper.py
  src/apps/comment/repository.py
  src/data_access/mappers/__init__.py
  src/data_access/mappers/comment_converter.py
  src/data_access/mappers/comment_mapper.py
  src/data_access/models/comment.py
  src/data_access/models/user.py
  src/data_access/repositories/__init__.py
  src/data_access/repositories/comment.py
  src/data_access/repositories/comment_repository.py
  src/main.py
  src/providers/adapters.py
  src/providers/usecases.py
Labels: enhancement, refactoring

#59 Feature context refactoring completed
  src/api/controllers/feature.py
  src/api/dtos/feature.py
  src/apps/feature/__init__.py
  src/apps/feature/domain/__init__.py
  src/apps/feature/domain/entities/__init__.py
  src/apps/feature/domain/feature.py
  src/apps/feature/domain/types_ids.py
  src/apps/feature/dtos.py
  src/apps/feature/exceptions.py
  src/apps/feature/interactors/__init__.py
  src/apps/feature/interactors/base_interactor.py
  src/apps/feature/interactors/create_feature.py
  src/apps/feature/interactors/delete_feature.py
  src/apps/feature/interactors/get_feature_by_id.py
  src/apps/feature/interactors/get_features.py
  src/apps/feature/interactors/get_features_by_workspace_id.py
  src/apps/feature/interactors/update_feature.py
  src/apps/feature/mapper.py
  src/apps/feature/query_parameters.py
  src/apps/feature/repositories/__init__.py
  src/apps/feature/repository.py
  src/data_access/mappers/feature_converter.py
  src/data_access/mappers/feature_mapper.py
  src/data_access/models/feature.py
  src/data_access/repositories/feature_repository.py
  src/providers/adapters.py
  src/providers/usecases.py
Labels: enhancement, refactoring

#60 Task context refactoring completed
  src/api/controllers/task.py
  src/api/dtos/task.py
  src/apps/task/__init__.py
  src/apps/task/domain/__init__.py
  src/apps/task/domain/entities/__init__.py
  src/apps/task/domain/task.py
  src/apps/task/domain/types_ids.py
  src/apps/task/dtos.py
  src/apps/task/exceptions.py
  src/apps/task/interactors/base_interactor.py
  src/apps/task/interactors/create_task.py
  src/apps/task/interactors/delete_task.py
  src/apps/task/interactors/get_task_by_id.py
  src/apps/task/interactors/get_tasks.py
  src/apps/task/interactors/get_tasks_by_feature_id.py
  src/apps/task/interactors/update_task.py
  src/apps/task/mapper.py
  src/apps/task/query_parameters.py
  src/apps/task/repositories/__init__.py
  src/apps/task/repository.py
  src/data_access/mappers/task_converter.py
  src/data_access/mappers/task_mapper.py
  src/data_access/models/task.py
  src/data_access/repositories/task_repository.py
  src/providers/adapters.py
  src/providers/usecases.py
Labels: enhancement, refactoring

#61 fix(workspace): fix function name
  src/api/controllers/workspace_invite.py
Labels: invalid
